#!/usr/bin/env python3
"""Regenerate the healing-hertz wordmark from the app's typeface.

The letterforms ship as outlines rather than text, so the mark never depends on
a font being installed — which matters most in the README, where GitHub renders
the SVG with no stylesheet of ours in reach. That makes the mark a build
artifact, and this is the only thing that builds it: the three files it writes
say "do not edit by hand" and mean it.

Writes:
    frontend/src/components/BrandMark.tsx   the in-app mark, themed
    docs/wordmark-dark.svg                  README, dark scheme
    docs/wordmark-light.svg                 README, light scheme

Needs the font, which comes from the frontend's dependencies, and fontTools:

    cd frontend && npm install
    python3 -m venv /tmp/ft && /tmp/ft/bin/pip install fonttools brotli
    /tmp/ft/bin/python scripts/gen-wordmark.py

To restyle the mark, change WEIGHT or SIZE and re-run. Everything downstream —
glyph outlines, letter positions, the viewBox — is derived, so nothing else
needs touching.
"""
from pathlib import Path

from fontTools.misc.transform import Transform
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = Path(__file__).resolve().parent.parent
WOFF2 = (ROOT / "frontend/node_modules/@fontsource-variable/outfit/files"
              / "outfit-latin-wght-normal.woff2")

WEIGHT = 600        # a geometric sans needs more weight than a serif to hold at 21px
SIZE = 18.0         # type size, in the viewBox's units
BASELINE = 16.0     # y of the baseline, unchanged from the Georgia original
START_X = 32.0      # first letter, clear of the signal glyph and its dot
PAD_RIGHT = 5.0
WORD1, WORD2 = "healing", "hertz"

# A noisy signal settling into a steady line: the diagnosis, then the fix.
SIGNAL = "M1 11 H4 L6.2 4.6 L8.8 17.6 L11.2 7.2 L13.2 14 L15 11 H20.4"

if not WOFF2.exists():
    raise SystemExit(f"font not found: {WOFF2}\nrun `npm install` in frontend/ first")

font = instancer.instantiateVariableFont(TTFont(WOFF2), {"wght": WEIGHT})
scale = SIZE / font["head"].unitsPerEm
cmap = font.getBestCmap()
glyphs = font.getGlyphSet()
hmtx = font["hmtx"]

# Flip the y axis — SVG counts down, a font counts up — and drop the baseline
# where the Georgia outlines had it, so the mark keeps its optical position.
xform = Transform(scale, 0, 0, -scale, 0, BASELINE)


def outline(ch: str) -> str:
    pen = SVGPathPen(glyphs, ntos=lambda v: f"{v:.2f}".rstrip("0").rstrip("."))
    glyphs[cmap[ord(ch)]].draw(TransformPen(pen, xform))
    return pen.getCommands()


def advance(ch: str) -> float:
    return hmtx[cmap[ord(ch)]][0] * scale


def lay_out(word: str, x: float) -> tuple[list[tuple[str, float]], float]:
    placed = []
    for ch in word:
        placed.append((ch, round(x, 2)))
        x += advance(ch)
    return placed, x


letters = sorted(set(WORD1 + WORD2))
defs = "\n".join(f'        <path id="hh-{c}" d="{outline(c)}" />' for c in letters)

first, x = lay_out(WORD1, START_X)
second, x = lay_out(WORD2, x + advance(" "))
width = round(x + PAD_RIGHT, 2)


def uses(placed, brace: bool) -> str:
    fmt = 'x={{{}}}' if brace else 'x="{}"'
    return "\n".join(f'        <use href="#hh-{c}" {fmt.format(x)} />' for c, x in placed)


(ROOT / "frontend/src/components/BrandMark.tsx").write_text(f'''/** The healing-hertz wordmark.
 *
 * The letterforms are outlines, not text. That began as a way to survive Trail
 * restyling headings to a serif; it still holds, because the same mark has to
 * render in the README, where no stylesheet of ours reaches it. Colour does
 * follow the theme — the mark and "healing" take currentColor, "hertz" takes
 * the accent.
 *
 * Outfit at {WEIGHT}, {SIZE:.0f}px, converted to paths and de-duplicated into <defs>,
 * so a repeated letter costs one <use> rather than a second copy.
 *
 * Generated by scripts/gen-wordmark.py — do not edit by hand.
 */
export default function BrandMark() {{
  return (
    <svg
      className="brandmark"
      viewBox="0 0 {width} 22"
      role="img"
      aria-label="healing hertz"
      focusable="false"
    >
      <defs>
{defs}
      </defs>
      <path
        d="{SIGNAL}"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.7"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle cx="23.2" cy="11" r="1.8" fill="var(--accent)" />
      <g fill="currentColor">
{uses(first, True)}
      </g>
      <g fill="var(--accent)">
{uses(second, True)}
      </g>
    </svg>
  );
}}
''')

# The README pair carries Trail's palette because that is what the repository
# page is dressed in; it is not tied to whichever theme the app opens in.
for name, ink, accent in [("dark", "#f5f5f5", "#a78bfa"), ("light", "#18181b", "#7c3aed")]:
    (ROOT / f"docs/wordmark-{name}.svg").write_text(
        f'''<!-- Generated by scripts/gen-wordmark.py — do not edit by hand. -->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="{round(width * 3)}" height="66"
      class="brandmark"
      viewBox="0 0 {width} 22"
      role="img"
      aria-label="healing hertz"
    >
      <defs>
{defs}
      </defs>
      <path
        d="{SIGNAL}"
        fill="none"
        stroke="{ink}"
        stroke-width="1.7"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <circle cx="23.2" cy="11" r="1.8" fill="{accent}" />
      <g fill="{ink}">
{uses(first, False)}
      </g>
      <g fill="{accent}">
{uses(second, False)}
      </g>
    </svg>
''')

print(f"Outfit {WEIGHT} at {SIZE:g}px — viewBox 0 0 {width} 22")
print(f"  glyphs: {' '.join(letters)}")
print(f"  {WORD1}: {first}")
print(f"  {WORD2}: {second}")
